// This is a simple example of how to use the API (api-shop)

### POST Shop register (Token admin loged in)
POST http://localhost:3000/api-shop/shopAdminRegister HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjcxZGU0YjAwY2Y1ODU4YzFhMmFhIiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNzE1MTU0NDU5LCJleHAiOjE3MTUxNjE2NTl9.iwCEHxNsv3J0mRRzdI65p4NvTWIxvlbYCpkpzxaHWRM

{
    "cif": "qtyw",
    "name": "Shop7",
    "email": "shop7@example.com",
    "password": "Password123!",
    "city": "NewYork",
    "activity": "Programming",
    "phone": "12341234"
}

### Update Shop (Token admin loged in)
PUT  http://localhost:3000/api-shop/shopAdmin/662b894f273d780098c6e082 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjcxZGU0YjAwY2Y1ODU4YzFhMmFhIiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNzE0MTI4ODk2LCJleHAiOjE3MTQxMzYwOTZ9.0g9Q07DAaiJa9SW7a69vhs9yv6NOfy0lfhh77IiYoQY

{
    "cif": "ABC12345678",
    "name": "Test_Shop",
    "email": "test@exampl.com",
    "password": "Password123!",
    "city": "Test_City",
    "activity": "Test_Activity",
    "phone": "123890"
}

### Get Shop (Token admin loged in)
GET http://localhost:3000/api-shop/shopAdmin HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjcxZGU0YjAwY2Y1ODU4YzFhMmFhIiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNzE0NDUzMDUzLCJleHAiOjE3MTQ0NjAyNTN9.BbSiuNEJgRLBs3RZOOZBD8Il-fxWzfAK8olr7UB13yI

### Get Shop by id (Token admin loged in)
GET http://localhost:3000/api-shop/shopAdmin/662b894f273d780098c6e082 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjcxZGU0YjAwY2Y1ODU4YzFhMmFhIiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNzE0NDUzMDUzLCJleHAiOjE3MTQ0NjAyNTN9.BbSiuNEJgRLBs3RZOOZBD8Il-fxWzfAK8olr7UB13yI

### PATCH Shop (Token admin loged in)
PATCH http://localhost:3000/api-shop/shopAdmin/662b894f273d780098c6e082 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjcxZGU0YjAwY2Y1ODU4YzFhMmFhIiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNzE0NDUzMDUzLCJleHAiOjE3MTQ0NjAyNTN9.BbSiuNEJgRLBs3RZOOZBD8Il-fxWzfAK8olr7UB13yI

{
    "cif": "A"
}

### DELETE Shop (Token admin loged in)
DELETE http://localhost:3000/api-shop/shopAdmin/663b2e604c4799c906ac5ca2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjcxZGU0YjAwY2Y1ODU4YzFhMmFhIiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNzE1MTU0NDU5LCJleHAiOjE3MTUxNjE2NTl9.iwCEHxNsv3J0mRRzdI65p4NvTWIxvlbYCpkpzxaHWRM

### Login Shop --> token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDEzMTQ1OSwiZXhwIjoxNzE0MTM4NjU5fQ.Vgl747MGUCweD71O6kY_476yVUnVdb4bGdpPfrlfhvc
POST http://localhost:3000/api-shop/shop/login HTTP/1.1
Content-Type: application/json

{
    "email": "shop4@example.com",
    "password": "Password123!"
}

### Update Shop (Token shop loged in)
PUT  http://localhost:3000/api-shop/shop/shop/662b894f273d780098c6e082 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDEzMTQ1OSwiZXhwIjoxNzE0MTM4NjU5fQ.Vgl747MGUCweD71O6kY_476yVUnVdb4bGdpPfrlfhvc

{
    "cif": "ABC12",
    "name": "Test_Shop",
    "email": "test@example.com",
    "password": "Password123!",
    "city": "Test_City",
    "activity": "Test_Activity",
    "phone": "1234567890"
}

### PATCH Shop (Token shop loged in)
PATCH http://localhost:3000/api-shop/shop/shop/662b894f273d780098c6e082 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDQ1MzI4MSwiZXhwIjoxNzE0NDYwNDgxfQ.hF2Np0lFpb0rQmMzaQKqyL63B1X_j6AFgbLFp3h1uyY

{
    "cif": "ABC12"
}

### DELETE Shop (Token shop loged in)
DELETE http://localhost:3000/api-shop/shop/shop/662b894f273d780098c6e082 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDEzMTQ1OSwiZXhwIjoxNzE0MTM4NjU5fQ.Vgl747MGUCweD71O6kY_476yVUnVdb4bGdpPfrlfhvc

### Get Shop User (regisred user and unregistered user)
GET http://localhost:3000/api-shop/sho/search/

### Get Shop User (regisred user and unregistered user) by id
GET http://localhost:3000/api-shop/shop/search/id/66320ea1f6cf493c1a7f81a0 HTTP/1.1

### Get Shop User (regisred user and unregistered user) by city
GET http://localhost:3000/api-shop/shop/search/city/Miami HTTP/1.1

### Get Shop User (regisred user and unregistered user) by activity
GET http://localhost:3000/api-shop/shop/search/activity/Music HTTP/1.1

### Get Shop User (regisred user and unregistered user) by name
GET http://localhost:3000/api-shop/shop/search/name/Shop1 HTTP/1.1

### Get Shop User (regisred user and unregistered user) by city and activity
GET http://localhost:3000/api-shop/shop/search/cityActivity/Miami/Music HTTP/1.1

### Get Shop User (regisred user and unregistered user) by city and activity and score (query)
GET http://localhost:3000/api-shop/shop/search/score?score=false&city=Miami

### Get Shop User (regisred user and unregistered user) by city and activity and score (query)
GET http://localhost:3000/api-shop/shop/search/score?score=true&activity=Programming

### Post WebShop (token shop loged in)
POST http://localhost:3000/api-shop/webShop/66320e7df6cf493c1a7f819d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYzMjBlN2RmNmNmNDkzYzFhN2Y4MTlkIn0sImlhdCI6MTcxNDU1NzAxNCwiZXhwIjoxNzE0NTY0MjE0fQ.hqhene9dt29IK4zUqLMWbB5t98O3i8SZuTDVI1KTlTw

{  
    "title": "WebShop 3", 
    "summary": "This is a web shop 3", 
    "texts": ["Lorem ipsum dolor sit amet", "consectetur adipiscing elit"], 
    "photos": ["photo1.jpg", "photo5.jpg"], 
    "scoring": 2, 
    "numRatings": 1, 
    "reviews": [ { "score": 2, "text": "Great shop!" }] 
}

### PUT WebShop (token shop loged in)
PUT http://localhost:3000/api-shop/webShop/662b894f273d780098c6e082 HTTP/1.
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYzMjBkZThmNmNmNDkzYzFhN2Y4MTk3In0sImlhdCI6MTcxNDU1NjgyOSwiZXhwIjoxNzE0NTY0MDI5fQ.fmbwwoz5EWeMVtsFSzZMGvsz6heK6DY7s89YJPqIZrU

{  
    "title": "Example ", 
    "summary": "This is an example web shop", 
    "texts": ["Lorem ipsum dolor sit amet", "consectetur adipiscing elit"], 
    "photos": ["photo1.jpg", "photo2.jpg"], 
    "scoring": 4.5, 
    "numRatings": 2, 
    "reviews": [ { "score": 5, "text": "Great shop!" }, { "score": 4, "text": "Good products" } ] 
}

### PATCH WebShop (token shop loged in)
PATCH http://localhost:3000/api-shop/webShop/662b894f273d780098c6e082 HTTP/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDQ1MzI4MSwiZXhwIjoxNzE0NDYwNDgxfQ.hF2Np0lFpb0rQmMzaQKqyL63B1X_j6AFgbLFp3h1uyY

{
    "title": "ExampleWebShop"
}

### DELETE WebShop (token shop loged in)
DELETE http://localhost:3000/api-shop/webShop/662b894f273d780098c6e082 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDE1Mjk5NiwiZXhwIjoxNzE0MTYwMTk2fQ.MydSfa9oQlV2BR559AZRrgFjxkevX8Ln4ES0mouwNxU

### Patch WebShop Photo (token shop loged in)
PATCH  http://localhost:3000/api-shop/webShop/662b894f273d780098c6e082/photo HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDQ1MzI4MSwiZXhwIjoxNzE0NDYwNDgxfQ.hF2Np0lFpb0rQmMzaQKqyL63B1X_j6AFgbLFp3h1uyY

{
    "photo": "photo3.jpg"
}

### Patch WebShop Text (token shop loged in)
PATCH  http://localhost:3000/api-shop/webShop/66320e7df6cf493c1a7f819d/text HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYzMjBlN2RmNmNmNDkzYzFhN2Y4MTlkIn0sImlhdCI6MTcxNTE1NDY3OCwiZXhwIjoxNzE1MTYxODc4fQ.MzPH1n5zsGq0xStPuo_xpPA2LYNq_rWkvVYyBhc4CEU

{
    "text": "this is a new text"
}

### Get WebShop Photos (token shop loged in)
GET http://localhost:3000/api-shop/webShop/662b894f273d780098c6e082/photo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDE1Mjk5NiwiZXhwIjoxNzE0MTYwMTk2fQ.MydSfa9oQlV2BR559AZRrgFjxkevX8Ln4ES0mouwNxU

### Get WebShop Texts (token shop loged in)
GET http://localhost:3000/api-shop/webShop/662b894f273d780098c6e082/text HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDE1Mjk5NiwiZXhwIjoxNzE0MTYwMTk2fQ.MydSfa9oQlV2BR559AZRrgFjxkevX8Ln4ES0mouwNxU

### Get WebShop Reviews (token shop loged in)
GET http://localhost:3000/api-shop/webShop/662b894f273d780098c6e082/reviews HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYyYjg5NGYyNzNkNzgwMDk4YzZlMDgyIn0sImlhdCI6MTcxNDE1MTM3MiwiZXhwIjoxNzE0MTU4NTcyfQ.2Pw3r_sHVhuXZ_uVLHz9XEYSuM_P5lqUIdahzhedGgc

### Patch WebShop Review  (token shop loged in)
PATCH  http://localhost:3000/api-shop/postReview/66320e7df6cf493c1a7f819d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOnsiX2lkIjoiNjYzYjMwZmQ0YzQ3OTljOTA2YWM1Y2UzIiwibmFtZSI6IkRvZSIsImVtYWlsIjoidXNlcjhAZXhhbGUuY29tIiwicm9sZSI6InVzZXIifSwiaWF0IjoxNzE1MTU1MjYyLCJleHAiOjE3MTUxNjI0NjJ9.DnTlz0DREKvasdMN8Y383zF3kzATkAYCz4M8VVvzOhw

{  
    "score": 4, 
    "text": "prueba" 
}